# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addendanceRecord.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QMessageBox

from clock.interface.recordSetting import RecordSetting
from interface.dayRecordSetting import DayRecordSetting
from interface.monthRecordSetting import MonthRecordSetting


class Ui_addendanceRecord(QMainWindow):
    def setupUi(self, addendanceRecord):
        addendanceRecord.setObjectName("addendanceRecord")
        addendanceRecord.resize(597, 260)
        self.centralwidget = QtWidgets.QWidget(addendanceRecord)
        self.centralwidget.setObjectName("centralwidget")
        self.alert = QtWidgets.QLabel(self.centralwidget)
        self.alert.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.alert.setObjectName("alert")
        self.tittle = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.tittle.setGeometry(QtCore.QRect(10, 10, 185, 41))
        self.tittle.setObjectName("tittle")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 90, 491, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dayRecord = QtWidgets.QPushButton(self.widget)
        self.dayRecord.setObjectName("dayRecord")
        self.horizontalLayout.addWidget(self.dayRecord)
        self.monthRecord = QtWidgets.QPushButton(self.widget)
        self.monthRecord.setObjectName("monthRecord")
        self.horizontalLayout.addWidget(self.monthRecord)
        self.recordSetting = QtWidgets.QPushButton(self.widget)
        self.recordSetting.setObjectName("recordSetting")
        self.horizontalLayout.addWidget(self.recordSetting)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(140, 170, 281, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back = QtWidgets.QPushButton(self.widget1)
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        self.exit = QtWidgets.QPushButton(self.widget1)
        self.exit.setObjectName("exit")
        self.horizontalLayout_2.addWidget(self.exit)
        addendanceRecord.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(addendanceRecord)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 21))
        self.menubar.setObjectName("menubar")
        addendanceRecord.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(addendanceRecord)
        self.statusbar.setObjectName("statusbar")
        addendanceRecord.setStatusBar(self.statusbar)

        self.exit.clicked.connect(self.close)
        self.retranslateUi(addendanceRecord)
        QtCore.QMetaObject.connectSlotsByName(addendanceRecord)

    def retranslateUi(self, addendanceRecord):
        _translate = QtCore.QCoreApplication.translate
        addendanceRecord.setWindowTitle(_translate("addendanceRecord", "MainWindow"))
        self.alert.setText(_translate("addendanceRecord", "请选择..."))
        self.tittle.setText(_translate("addendanceRecord", "考勤报表功能菜单"))
        self.dayRecord.setText(_translate("addendanceRecord", "日报"))
        self.monthRecord.setText(_translate("addendanceRecord", "月报"))
        self.recordSetting.setText(_translate("addendanceRecord", "报表设置"))
        self.back.setText(_translate("addendanceRecord", "返回"))
        self.exit.setText(_translate("addendanceRecord", "退出"))

    def close(self):
        result = QMessageBox.information(self, '信息', '确定退出吗？', QMessageBox.Yes | QMessageBox.No)
        if result == QMessageBox.Yes:
            sys.exit()


class AddendanceRecord(QMainWindow):
    def __init__(self, parent=None):
        super(AddendanceRecord, self).__init__(parent)
        self.addendanceRecord = Ui_addendanceRecord()
        self.addendanceRecord.setupUi(self)
        self.addendanceRecord.back.clicked.connect(self.back)
        self.addendanceRecord.recordSetting.clicked.connect(self.show_recordSetting)
        self.addendanceRecord.dayRecord.clicked.connect(self.getDayRecord)
        self.addendanceRecord.monthRecord.clicked.connect(self.getMonthRecord)

    def back(self):
        from main import Main
        self.hide()
        self.main = Main()
        self.main.show()

    def show_recordSetting(self):
        self.hide()
        self.recordSetting = RecordSetting()
        self.recordSetting.show()

    def getDayRecord(self):
        self.dayRecordSetting = DayRecordSetting()
        self.dayRecordSetting.show()

    def getMonthRecord(self):
        self.monthRecordSetting = MonthRecordSetting()
        self.monthRecordSetting.show()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    addendanceRecord = AddendanceRecord()
    addendanceRecord.show()
    sys.exit(app.exec_())
