# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkInRecordSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication

import operateMain as op
from util import public_tools as pt


class Ui_checkInRecordSetting(QMainWindow):
    def setupUi(self, checkInRecordSetting):
        checkInRecordSetting.setObjectName("checkInRecordSetting")
        checkInRecordSetting.resize(526, 171)
        self.submit = QtWidgets.QDialogButtonBox(checkInRecordSetting)
        self.submit.setGeometry(QtCore.QRect(180, 120, 156, 23))
        self.submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.submit.setObjectName("submit")
        self.today = QtWidgets.QCheckBox(checkInRecordSetting)
        self.today.setGeometry(QtCore.QRect(96, 63, 71, 16))
        self.today.setObjectName("today")
        self.splitter = QtWidgets.QSplitter(checkInRecordSetting)
        self.splitter.setGeometry(QtCore.QRect(260, 60, 161, 21))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.someDay = QtWidgets.QDateEdit(self.splitter)
        self.someDay.setObjectName("someDay")

        self.retranslateUi(checkInRecordSetting)
        QtCore.QMetaObject.connectSlotsByName(checkInRecordSetting)

    def retranslateUi(self, checkInRecordSetting):
        _translate = QtCore.QCoreApplication.translate
        checkInRecordSetting.setWindowTitle(_translate("checkInRecordSetting", "Form"))
        self.today.setText(_translate("checkInRecordSetting", "今天"))
        self.label.setText(_translate("checkInRecordSetting", "指定："))


class CheckInRecordSettig(QMainWindow):
    def __init__(self, parent=None):
        super(CheckInRecordSettig, self).__init__(parent)
        self.checkInRecordSetting = Ui_checkInRecordSetting()
        self.checkInRecordSetting.setupUi(self)
        self.checkInRecordSetting.submit.accepted.connect(self.onAccepted)
        self.checkInRecordSetting.submit.rejected.connect(self.onRejected)
        self.checkInRecordSetting.today.clicked.connect(self.checkDay)

    def onAccepted(self):
        if self.checkInRecordSetting.today.isChecked():
            op.check_record()
        else:
            day = self.checkInRecordSetting.someDay.text()
            day = pt.modformat(day)
            op.check_record(day)

    def onRejected(self):
        self.close()

    def checkDay(self):
        if self.checkInRecordSetting.today.isChecked():
            self.checkInRecordSetting.someDay.setEnabled(False)
        else:
            self.checkInRecordSetting.someDay.setEnabled(True)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    checkRecordSetting = CheckInRecordSettig()
    checkRecordSetting.show()
    sys.exit(app.exec_())