# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkInManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QMessageBox


class Ui_checkInManage(QMainWindow):
    def setupUi(self, checkInManage):
        checkInManage.setObjectName("checkInManage")
        checkInManage.resize(599, 258)
        self.layoutWidget = QtWidgets.QWidget(checkInManage)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 110, 491, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.employeeList = QtWidgets.QPushButton(self.layoutWidget)
        self.employeeList.setObjectName("employeeList")
        self.horizontalLayout.addWidget(self.employeeList)
        self.checkInRecord = QtWidgets.QPushButton(self.layoutWidget)
        self.checkInRecord.setObjectName("checkInRecord")
        self.horizontalLayout.addWidget(self.checkInRecord)
        self.layoutWidget_2 = QtWidgets.QWidget(checkInManage)
        self.layoutWidget_2.setGeometry(QtCore.QRect(160, 180, 281, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back = QtWidgets.QPushButton(self.layoutWidget_2)
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        self.exit = QtWidgets.QPushButton(self.layoutWidget_2)
        self.exit.setObjectName("exit")
        self.horizontalLayout_2.addWidget(self.exit)
        self.alert = QtWidgets.QLabel(checkInManage)
        self.alert.setGeometry(QtCore.QRect(30, 70, 101, 16))
        self.alert.setObjectName("alert")
        self.tittle = QtWidgets.QCommandLinkButton(checkInManage)
        self.tittle.setGeometry(QtCore.QRect(20, 20, 185, 41))
        self.tittle.setObjectName("tittle")

        self.exit.clicked.connect(self.close)
        self.retranslateUi(checkInManage)
        QtCore.QMetaObject.connectSlotsByName(checkInManage)

    def retranslateUi(self, checkInManage):
        _translate = QtCore.QCoreApplication.translate
        checkInManage.setWindowTitle(_translate("checkInManage", "Form"))
        self.employeeList.setText(_translate("checkInManage", "查看员工列表"))
        self.checkInRecord.setText(_translate("checkInManage", "查看打卡记录"))
        self.back.setText(_translate("checkInManage", "返回"))
        self.exit.setText(_translate("checkInManage", "退出"))
        self.alert.setText(_translate("checkInManage", "请选择..."))
        self.tittle.setText(_translate("checkInManage", "查看记录功能菜单"))

    def close(self):
        result = QMessageBox.information(self, '信息', '确定退出吗？', QMessageBox.Yes | QMessageBox.No)
        if result == QMessageBox.Yes:
            sys.exit()


class CheckInManage(QMainWindow):
    def __init__(self, parent=None):
        super(CheckInManage, self).__init__(parent)
        self.checkInManage = Ui_checkInManage()
        self.checkInManage.setupUi(self)
        self.checkInManage.back.clicked.connect(self.back)

    def back(self):
        from main import Main
        self.hide()
        self.main = Main()
        self.main.show()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    checkInManage = CheckInManage()
    checkInManage.show()
    sys.exit(app.exec_())