# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dayRecordSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

import operateMain as op
from util import public_tools as pt


class Ui_dayRecordSetting(QMainWindow):
    def setupUi(self, dayRecordSetting):
        dayRecordSetting.setObjectName("dayRecordSetting")
        dayRecordSetting.resize(525, 172)
        self.submit = QtWidgets.QDialogButtonBox(dayRecordSetting)
        self.submit.setGeometry(QtCore.QRect(160, 120, 156, 23))
        self.submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.submit.setObjectName("submit")
        self.splitter = QtWidgets.QSplitter(dayRecordSetting)
        self.splitter.setGeometry(QtCore.QRect(240, 60, 161, 21))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.someDay = QtWidgets.QDateEdit(self.splitter)
        self.someDay.setObjectName("someDay")
        self.today = QtWidgets.QCheckBox(dayRecordSetting)
        self.today.setGeometry(QtCore.QRect(110, 64, 71, 16))
        self.today.setObjectName("today")

        self.retranslateUi(dayRecordSetting)
        QtCore.QMetaObject.connectSlotsByName(dayRecordSetting)

    def retranslateUi(self, dayRecordSetting):
        _translate = QtCore.QCoreApplication.translate
        dayRecordSetting.setWindowTitle(_translate("dayRecordSetting", "Form"))
        self.label.setText(_translate("dayRecordSetting", "指定："))
        self.today.setText(_translate("dayRecordSetting", "今天"))

class DayRecordSetting(QMainWindow):
    def __init__(self, parent=None):
        super(DayRecordSetting, self).__init__(parent)
        self.dayRecordSetting = Ui_dayRecordSetting()
        self.dayRecordSetting.setupUi(self)
        self.dayRecordSetting.submit.accepted.connect(self.onAccepted)
        self.dayRecordSetting.submit.rejected.connect(self.onRejected)
        self.dayRecordSetting.today.clicked.connect(self.checkDay)

    def checkDay(self):
        if self.dayRecordSetting.today.isChecked():
            self.dayRecordSetting.someDay.setEnabled(False)
        else:
            self.dayRecordSetting.someDay.setEnabled(True)

    def onAccepted(self):
        if self.dayRecordSetting.today.isChecked():
            op.check_day_report()
        else:
            date = self.dayRecordSetting.someDay.text()
            date = pt.modformat(date)
            op.check_day_report(date)

    def onRejected(self):
        self.close()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    dayRecordSetting = DayRecordSetting()
    dayRecordSetting.show()
    sys.exit(app.exec_())