# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox, QMainWindow

from interface.identityUser import IdentityUser
from entity import organizations as o
from service import hr_service as hr


class Ui_deleteEmployee(QMainWindow):
    def setupUi(self, deleteEmployee):
        deleteEmployee.setObjectName("deleteEmployee")
        deleteEmployee.resize(524, 171)
        self.submit = QtWidgets.QDialogButtonBox(deleteEmployee)
        self.submit.setGeometry(QtCore.QRect(170, 110, 161, 41))
        self.submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.submit.setObjectName("submit")
        self.splitter = QtWidgets.QSplitter(deleteEmployee)
        self.splitter.setGeometry(QtCore.QRect(294, 64, 114, 12))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.employeeName = QtWidgets.QLabel(self.splitter)
        self.employeeName.setObjectName("employeeName")
        self.label = QtWidgets.QLabel(deleteEmployee)
        self.label.setGeometry(QtCore.QRect(78, 63, 48, 16))
        self.label.setObjectName("label")
        self.employeeId = QtWidgets.QComboBox(deleteEmployee)
        self.employeeId.setGeometry(QtCore.QRect(135, 60, 91, 20))
        self.employeeId.setEditable(True)
        self.employeeId.setObjectName("employeeId")
        self.employeeId.addItem("")
        for item in o.EMPLOYEES:
            self.employeeId.addItem(str(item.id))
        self.retranslateUi(deleteEmployee)
        QtCore.QMetaObject.connectSlotsByName(deleteEmployee)

    def retranslateUi(self, deleteEmployee):
        _translate = QtCore.QCoreApplication.translate
        deleteEmployee.setWindowTitle(_translate("deleteEmployee", "Form"))
        self.label_2.setText(_translate("deleteEmployee", "员工姓名："))
        self.employeeName.setText(_translate("deleteEmployee", "————"))
        self.label.setText(_translate("deleteEmployee", "员工id："))
        self.employeeId.setItemText(0, _translate("deleteEmployee", "请选择..."))


class DeleteEmployee(QMainWindow):
    def __init__(self, parent=None):
        super(DeleteEmployee, self).__init__(parent)
        self.deleteEmployee = Ui_deleteEmployee()
        self.deleteEmployee.setupUi(self)
        self.deleteEmployee.submit.accepted.connect(self.onAccepted)
        self.deleteEmployee.submit.rejected.connect(self.onRejected)
        self.deleteEmployee.employeeId.currentIndexChanged.connect(self.changeEmployName)

    def onAccepted(self):
        result = QMessageBox.information(self, '信息', '确定删除吗？', QMessageBox.Yes | QMessageBox.No)
        if result == QMessageBox.Yes:
            id = self.deleteEmployee.employeeId.currentText()
            self.identityUser = IdentityUser(id=id)
            self.identityUser.show()

    def onRejected(self):
        self.close()

    def changeEmployName(self):
        id = self.deleteEmployee.employeeId.currentText()
        name = hr.get_name_with_id(id)
        self.deleteEmployee.employeeName.setText(str(name))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    deleteEmployee = DeleteEmployee()
    deleteEmployee.show()
    sys.exit(app.exec_())
