# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employeeManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QMainWindow, QApplication
from interface.deleteEmployee import DeleteEmployee
from interface.setEmployeeInfo import SetEmployeeInfo


class Ui_employeeManage(QMainWindow):
    def setupUi(self, employeeManage):
        employeeManage.setObjectName("employeeManage")
        employeeManage.resize(597, 262)
        self.tittle = QtWidgets.QCommandLinkButton(employeeManage)
        self.tittle.setGeometry(QtCore.QRect(20, 20, 185, 41))
        self.tittle.setObjectName("tittle")
        self.alert = QtWidgets.QLabel(employeeManage)
        self.alert.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.alert.setObjectName("alert")
        self.layoutWidget_2 = QtWidgets.QWidget(employeeManage)
        self.layoutWidget_2.setGeometry(QtCore.QRect(150, 190, 281, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back = QtWidgets.QPushButton(self.layoutWidget_2)
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        self.exit = QtWidgets.QPushButton(self.layoutWidget_2)
        self.exit.setObjectName("exit")
        self.horizontalLayout_2.addWidget(self.exit)
        self.widget = QtWidgets.QWidget(employeeManage)
        self.widget.setGeometry(QtCore.QRect(70, 120, 491, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recordNewEmployee = QtWidgets.QPushButton(self.widget)
        self.recordNewEmployee.setObjectName("recordNewEmployee")
        self.horizontalLayout.addWidget(self.recordNewEmployee)
        self.deleteEmployee = QtWidgets.QPushButton(self.widget)
        self.deleteEmployee.setObjectName("deleteEmployee")
        self.horizontalLayout.addWidget(self.deleteEmployee)

        self.exit.clicked.connect(self.close)
        self.retranslateUi(employeeManage)
        QtCore.QMetaObject.connectSlotsByName(employeeManage)

    def retranslateUi(self, employeeManage):
        _translate = QtCore.QCoreApplication.translate
        employeeManage.setWindowTitle(_translate("employeeManage", "Form"))
        self.tittle.setText(_translate("employeeManage", "员工管理功能菜单"))
        self.alert.setText(_translate("employeeManage", "请选择..."))
        self.back.setText(_translate("employeeManage", "返回"))
        self.exit.setText(_translate("employeeManage", "退出"))
        self.recordNewEmployee.setText(_translate("employeeManage", "录入新员工"))
        self.deleteEmployee.setText(_translate("employeeManage", "删除员工"))

    def close(self):
        result = QMessageBox.information(self, '信息', '确定退出吗？', QMessageBox.Yes | QMessageBox.No)
        if result == QMessageBox.Yes:
            sys.exit()


class EmployeeManage(QMainWindow):
    def __init__(self, parent=None):
        super(EmployeeManage, self).__init__(parent)
        self.employeeManage = Ui_employeeManage()
        self.employeeManage.setupUi(self)
        self.employeeManage.back.clicked.connect(self.back)
        self.employeeManage.deleteEmployee.clicked.connect(self.delete)
        self.employeeManage.recordNewEmployee.clicked.connect(self.register)

    def back(self):
        from main import Main
        self.hide()
        self.main = Main()
        self.main.show()

    def delete(self):
        self.delete = DeleteEmployee()
        self.delete.show()

    def register(self):
        self.setEmployeeInfo = SetEmployeeInfo()
        self.setEmployeeInfo.show()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    employeeManage = EmployeeManage()
    employeeManage.show()
    sys.exit(app.exec_())
