# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'identityUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QMessageBox, QApplication
from util import public_tools as tool
import operateMain as op


class Ui_identityUser(QMainWindow):
    def setupUi(self, identityUser):
        identityUser.setObjectName("identityUser")
        identityUser.resize(400, 140)
        self.submit = QtWidgets.QDialogButtonBox(identityUser)
        self.submit.setGeometry(QtCore.QRect(110, 95, 156, 23))
        self.submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.submit.setObjectName("submit")
        self.label = QtWidgets.QLabel(identityUser)
        self.label.setGeometry(QtCore.QRect(70, 20, 91, 16))
        self.label.setObjectName("label")
        self.identityCode = QtWidgets.QLabel(identityUser)
        self.identityCode.setGeometry(QtCore.QRect(180, 22, 54, 12))
        self.identityCode.setObjectName("identityCode")
        self.codeText = QtWidgets.QLineEdit(identityUser)
        self.codeText.setGeometry(QtCore.QRect(120, 50, 131, 20))
        self.codeText.setObjectName("codeText")

        verification = tool.randomNumber(4)  # 生成随机4位验证码
        self.identityCode.setText(str(verification))
        self.retranslateUi(identityUser)
        QtCore.QMetaObject.connectSlotsByName(identityUser)

    def retranslateUi(self, identityUser):
        _translate = QtCore.QCoreApplication.translate
        identityUser.setWindowTitle(_translate("identityUser", "Form"))
        self.label.setText(_translate("identityUser", "请在下方输入："))


class IdentityUser(QMainWindow):
    def __init__(self, parent=None, id=None):
        super(IdentityUser, self).__init__(parent)
        self.identityUser = Ui_identityUser()
        self.identityUser.setupUi(self)
        self.identityUser.submit.accepted.connect(self.onAccepted)
        self.identityUser.submit.rejected.connect(self.onRejected)
        self.id = id

    def onAccepted(self):
        text = self.identityUser.codeText.text()
        if text == self.identityUser.identityCode.text():
            op.deleteEmployee(self.id)

    def onRejected(self):
        self.close()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    identityUser = IdentityUser()
    identityUser.show()
    sys.exit(app.exec_())
