# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monthRecordSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QMessageBox

import operateMain as op


class Ui_monthRecordSetting(QMainWindow):
    def setupUi(self, monthRecordSetting):
        monthRecordSetting.setObjectName("monthRecordSetting")
        monthRecordSetting.resize(525, 170)
        self.submit = QtWidgets.QDialogButtonBox(monthRecordSetting)
        self.submit.setGeometry(QtCore.QRect(160, 120, 156, 23))
        self.submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.submit.setObjectName("submit")
        self.premonth = QtWidgets.QCheckBox(monthRecordSetting)
        self.premonth.setGeometry(QtCore.QRect(92, 62, 71, 16))
        self.premonth.setObjectName("premonth")
        self.someMonth = QtWidgets.QComboBox(monthRecordSetting)
        self.someMonth.setGeometry(QtCore.QRect(373, 60, 77, 20))
        self.someMonth.setAutoFillBackground(False)
        self.someMonth.setEditable(False)
        self.someMonth.setObjectName("someMonth")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.someMonth.addItem("")
        self.label_2 = QtWidgets.QLabel(monthRecordSetting)
        self.label_2.setGeometry(QtCore.QRect(354, 64, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(monthRecordSetting)
        self.label.setGeometry(QtCore.QRect(215, 63, 36, 16))
        self.label.setObjectName("label")
        self.year = QtWidgets.QComboBox(monthRecordSetting)
        self.year.setGeometry(QtCore.QRect(269, 60, 72, 20))
        self.year.setEditable(False)
        self.year.setObjectName("year")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")

        self.retranslateUi(monthRecordSetting)
        QtCore.QMetaObject.connectSlotsByName(monthRecordSetting)

    def retranslateUi(self, monthRecordSetting):
        _translate = QtCore.QCoreApplication.translate
        monthRecordSetting.setWindowTitle(_translate("monthRecordSetting", "Form"))
        self.premonth.setText(_translate("monthRecordSetting", "上个月"))
        self.someMonth.setItemText(0, _translate("monthRecordSetting", "请选择..."))
        self.someMonth.setItemText(1, _translate("monthRecordSetting", "01"))
        self.someMonth.setItemText(2, _translate("monthRecordSetting", "02"))
        self.someMonth.setItemText(3, _translate("monthRecordSetting", "03"))
        self.someMonth.setItemText(4, _translate("monthRecordSetting", "04"))
        self.someMonth.setItemText(5, _translate("monthRecordSetting", "05"))
        self.someMonth.setItemText(6, _translate("monthRecordSetting", "06"))
        self.someMonth.setItemText(7, _translate("monthRecordSetting", "07"))
        self.someMonth.setItemText(8, _translate("monthRecordSetting", "08"))
        self.someMonth.setItemText(9, _translate("monthRecordSetting", "09"))
        self.someMonth.setItemText(10, _translate("monthRecordSetting", "10"))
        self.someMonth.setItemText(11, _translate("monthRecordSetting", "11"))
        self.someMonth.setItemText(12, _translate("monthRecordSetting", "12"))
        self.label_2.setText(_translate("monthRecordSetting", "-"))
        self.label.setText(_translate("monthRecordSetting", "指定："))
        self.year.setItemText(0, _translate("monthRecordSetting", "请选择..."))
        self.year.setItemText(1, _translate("monthRecordSetting", "2000"))
        self.year.setItemText(2, _translate("monthRecordSetting", "2001"))
        self.year.setItemText(3, _translate("monthRecordSetting", "2002"))
        self.year.setItemText(4, _translate("monthRecordSetting", "2003"))
        self.year.setItemText(5, _translate("monthRecordSetting", "2004"))
        self.year.setItemText(6, _translate("monthRecordSetting", "2005"))
        self.year.setItemText(7, _translate("monthRecordSetting", "2006"))
        self.year.setItemText(8, _translate("monthRecordSetting", "2007"))
        self.year.setItemText(9, _translate("monthRecordSetting", "2008"))
        self.year.setItemText(10, _translate("monthRecordSetting", "2009"))
        self.year.setItemText(11, _translate("monthRecordSetting", "2010"))
        self.year.setItemText(12, _translate("monthRecordSetting", "2011"))
        self.year.setItemText(13, _translate("monthRecordSetting", "2012"))
        self.year.setItemText(14, _translate("monthRecordSetting", "2013"))
        self.year.setItemText(15, _translate("monthRecordSetting", "2014"))
        self.year.setItemText(16, _translate("monthRecordSetting", "2015"))
        self.year.setItemText(17, _translate("monthRecordSetting", "2016"))
        self.year.setItemText(18, _translate("monthRecordSetting", "2017"))
        self.year.setItemText(19, _translate("monthRecordSetting", "2018"))
        self.year.setItemText(20, _translate("monthRecordSetting", "2019"))
        self.year.setItemText(21, _translate("monthRecordSetting", "2020"))
        self.year.setItemText(22, _translate("monthRecordSetting", "2021"))


class MonthRecordSetting(QMainWindow):
    def __init__(self, parent=None):
        super(MonthRecordSetting, self).__init__(parent)
        self.monthRecordSetting = Ui_monthRecordSetting()
        self.monthRecordSetting.setupUi(self)
        self.monthRecordSetting.submit.accepted.connect(self.onAccepted)
        self.monthRecordSetting.submit.rejected.connect(self.onRejected)
        self.monthRecordSetting.premonth.clicked.connect(self.checkMonth)

    def checkMonth(self):
        if self.monthRecordSetting.premonth.isChecked():
            self.monthRecordSetting.someMonth.setEnabled(False)
            self.monthRecordSetting.year.setEnabled(False)
        else:
            self.monthRecordSetting.year.setEnabled(True)
            self.monthRecordSetting.someMonth.setEnabled(True)

    def onAccepted(self):
        if self.monthRecordSetting.premonth.isChecked():
            op.check_month_report()
        else:
            year = self.monthRecordSetting.year.currentText()
            month = self.monthRecordSetting.someMonth.currentText()
            if year == '请选择...' or month == '请选择...':
                QMessageBox.information(self, '信息', '请设置年和月', QMessageBox.Yes)
            else:
                op.check_month_report(str(year) + "-" + str(month))
            print(year+month)

    def onRejected(self):
        self.close()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    monRecordSetting = MonthRecordSetting()
    monRecordSetting.show()
    sys.exit(app.exec_())