# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QMessageBox, QApplication

from interface.userLogin import UserLogin


class Ui_recordSetting(QMainWindow):
    def setupUi(self, recordSetting):
        recordSetting.setObjectName("recordSetting")
        recordSetting.resize(599, 260)
        self.daytimeSetting = QtWidgets.QPushButton(recordSetting)
        self.daytimeSetting.setGeometry(QtCore.QRect(210, 120, 159, 23))
        self.daytimeSetting.setObjectName("daytimeSetting")
        self.layoutWidget = QtWidgets.QWidget(recordSetting)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 180, 281, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back = QtWidgets.QPushButton(self.layoutWidget)
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        self.exit = QtWidgets.QPushButton(self.layoutWidget)
        self.exit.setObjectName("exit")
        self.horizontalLayout_2.addWidget(self.exit)
        self.alert = QtWidgets.QLabel(recordSetting)
        self.alert.setGeometry(QtCore.QRect(40, 80, 101, 16))
        self.alert.setObjectName("alert")
        self.tittle = QtWidgets.QCommandLinkButton(recordSetting)
        self.tittle.setGeometry(QtCore.QRect(20, 20, 185, 41))
        self.tittle.setObjectName("tittle")

        self.exit.clicked.connect(self.close)
        self.retranslateUi(recordSetting)
        QtCore.QMetaObject.connectSlotsByName(recordSetting)

    def retranslateUi(self, recordSetting):
        _translate = QtCore.QCoreApplication.translate
        recordSetting.setWindowTitle(_translate("recordSetting", "Form"))
        self.daytimeSetting.setText(_translate("recordSetting", "作息时间设置"))
        self.back.setText(_translate("recordSetting", "返回"))
        self.exit.setText(_translate("recordSetting", "退出"))
        self.alert.setText(_translate("recordSetting", "请选择..."))
        self.tittle.setText(_translate("recordSetting", "报表设置功能菜单"))

    def close(self):
        result = QMessageBox.information(self, '信息', '确定退出吗？', QMessageBox.Yes | QMessageBox.No)
        if result == QMessageBox.Yes:
            sys.exit()


class RecordSetting(QMainWindow):
    def __init__(self, parent=None):
        super(RecordSetting, self).__init__(parent)
        self.recordSetting = Ui_recordSetting()
        self.recordSetting.setupUi(self)
        self.recordSetting.back.clicked.connect(self.back)
        self.recordSetting.daytimeSetting.clicked.connect(self.setTime)

    def back(self):
        from clock.interface.addendanceRecord import AddendanceRecord
        self.hide()
        self.addendanceRecord = AddendanceRecord()
        self.addendanceRecord.show()

    def setTime(self):
        self.userLogin = UserLogin(setTime=True)
        self.userLogin.show()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    recordSetting = RecordSetting()
    recordSetting.show()
    sys.exit(app.exec_())
