# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setEmployeeInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox, QMainWindow
import operateMain as op
from util import public_tools as pt


class Ui_setEmployeeInfo(QMainWindow):
    def setupUi(self, setEmployeeInfo):
        setEmployeeInfo.setObjectName("setEmployeeInfo")
        setEmployeeInfo.resize(524, 173)
        self.submit = QtWidgets.QDialogButtonBox(setEmployeeInfo)
        self.submit.setGeometry(QtCore.QRect(170, 131, 156, 23))
        self.submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.submit.setObjectName("submit")
        self.name = QtWidgets.QLineEdit(setEmployeeInfo)
        self.name.setGeometry(QtCore.QRect(220, 24, 191, 20))
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(setEmployeeInfo)
        self.label.setGeometry(QtCore.QRect(100, 24, 111, 20))
        self.label.setObjectName("label")
        self.registerImage = QtWidgets.QPushButton(setEmployeeInfo)
        self.registerImage.setGeometry(QtCore.QRect(196, 92, 101, 23))
        self.registerImage.setObjectName("registerImage")
        self.backInfo = QtWidgets.QLabel(setEmployeeInfo)
        self.backInfo.setGeometry(QtCore.QRect(196, 59, 131, 20))
        self.backInfo.setObjectName("backInfo")

        self.retranslateUi(setEmployeeInfo)
        QtCore.QMetaObject.connectSlotsByName(setEmployeeInfo)

    def retranslateUi(self, setEmployeeInfo):
        _translate = QtCore.QCoreApplication.translate
        setEmployeeInfo.setWindowTitle(_translate("setEmployeeInfo", "Form"))
        self.label.setText(_translate("setEmployeeInfo", "您的真实姓名："))
        self.registerImage.setText(_translate("setEmployeeInfo", "开始录入图像"))
        self.backInfo.setText(_translate("setEmployeeInfo", "点击按钮录入图像"))


class SetEmployeeInfo(QMainWindow):


    def __init__(self, parent=None):
        super(SetEmployeeInfo, self).__init__(parent)
        self.setEmployeeInfo = Ui_setEmployeeInfo()
        self.setEmployeeInfo.setupUi(self)
        self.setEmployeeInfo.submit.accepted.connect(self.onAccepted)
        self.setEmployeeInfo.submit.rejected.connect(self.onRejected)
        self.imageStatus = False
        self.employeeCode = None

    def onAccepted(self):
        name = self.setEmployeeInfo.name.text()
        if not pt.nameFormat(name):  # 对name进行校验
            QMessageBox.information(self, '信息', '请输入符合规范的真实姓名', QMessageBox.Yes)
        if not self.imageStatus:
            QMessageBox.information(self, '信息', '请重新录入图像', QMessageBox.Yes)
        else:
            op.registerEmployee(name, self.employeeCode)

    def onRejected(self):
        self.close()

    def registerImage(self):
        status, code = op.registerImage()
        self.employeeCode = code
        self.imageStatus = status
        if self.imageStatus:
            self.setEmployeeInfo.backInfo.setText("录入成功！！！")
        else:
            self.setEmployeeInfo.backInfo.setText("录入失败，请重新录入")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    setEmployeeInfo = SetEmployeeInfo()
    setEmployeeInfo.show()
    sys.exit(app.exec_())
