# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timeSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QMessageBox

from service import hr_service as hr
from util import public_tools as pt


class Ui_timeSetting(QMainWindow):
    def setupUi(self, timeSetting):
        timeSetting.setObjectName("timeSetting")
        timeSetting.resize(523, 173)
        self.submit = QtWidgets.QDialogButtonBox(timeSetting)
        self.submit.setGeometry(QtCore.QRect(180, 120, 156, 23))
        self.submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.submit.setObjectName("submit")
        self.splitter = QtWidgets.QSplitter(timeSetting)
        self.splitter.setGeometry(QtCore.QRect(70, 60, 141, 21))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.start = QtWidgets.QLabel(self.splitter)
        self.start.setObjectName("start")
        self.startEdit = QtWidgets.QTimeEdit(self.splitter)
        self.startEdit.setObjectName("startEdit")
        self.splitter_2 = QtWidgets.QSplitter(timeSetting)
        self.splitter_2.setGeometry(QtCore.QRect(280, 60, 131, 21))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.end = QtWidgets.QLabel(self.splitter_2)
        self.end.setObjectName("end")
        self.endEdit = QtWidgets.QTimeEdit(self.splitter_2)
        self.endEdit.setObjectName("endEdit")

        self.retranslateUi(timeSetting)
        QtCore.QMetaObject.connectSlotsByName(timeSetting)

    def retranslateUi(self, timeSetting):
        _translate = QtCore.QCoreApplication.translate
        timeSetting.setWindowTitle(_translate("timeSetting", "Form"))
        self.start.setText(_translate("timeSetting", "上班："))
        self.end.setText(_translate("timeSetting", "下班："))


class TimeSetting(QMainWindow):
    def __init__(self, parent=None):
        super(TimeSetting, self).__init__(parent)
        self.timeSetting = Ui_timeSetting()
        self.timeSetting.setupUi(self)
        self.timeSetting.submit.accepted.connect(self.onAccepted)
        self.timeSetting.submit.rejected.connect(self.onRejected)

    def onAccepted(self):
        start = self.timeSetting.startEdit.text()
        end = self.timeSetting.endEdit.text()
        start = pt.timeutc(start)
        end = pt.timeutc(end)
        if start >= end:
            QMessageBox.information(self, '信息', '请设置合理的时间（注意时间顺序）', QMessageBox.Yes)
        else:
            hr.save_work_time(str(start), str(end))

    def onRejected(self):
        self.close()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    timeSetting = TimeSetting()
    timeSetting.show()
    sys.exit(app.exec_())
