# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox

from interface.employeeManage import EmployeeManage
from interface.timeSetting import TimeSetting
import operateMain as op


class Ui_userLogin(QMainWindow):
    def setupUi(self, userLogin):
        userLogin.setObjectName("userLogin")
        userLogin.resize(526, 171)
        self.submit = QtWidgets.QDialogButtonBox(userLogin)
        self.submit.setGeometry(QtCore.QRect(170, 120, 156, 31))
        self.submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.submit.setObjectName("submit")
        self.usernameLabel = QtWidgets.QLabel(userLogin)
        self.usernameLabel.setGeometry(QtCore.QRect(80, 50, 48, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(userLogin)
        self.passwordLabel.setGeometry(QtCore.QRect(80, 80, 36, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.username = QtWidgets.QLineEdit(userLogin)
        self.username.setGeometry(QtCore.QRect(191, 49, 201, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(userLogin)
        self.password.setGeometry(QtCore.QRect(191, 79, 201, 20))
        self.password.setObjectName("password")

        self.retranslateUi(userLogin)
        QtCore.QMetaObject.connectSlotsByName(userLogin)

    def retranslateUi(self, userLogin):
        _translate = QtCore.QCoreApplication.translate
        userLogin.setWindowTitle(_translate("userLogin", "Form"))
        self.usernameLabel.setText(_translate("userLogin", "用户名："))
        self.passwordLabel.setText(_translate("userLogin", "密码："))


class UserLogin(QMainWindow):
    def __init__(self, parent=None, setTime=False):
        super(UserLogin, self).__init__(parent)
        self.userLogin = Ui_userLogin()
        self.userLogin.setupUi(self)
        self.userLogin.submit.rejected.connect(self.onRejected)
        self.userLogin.submit.accepted.connect(self.onAccepted)
        self.setTime = setTime

    def onRejected(self):
        self.close()

    def onAccepted(self):
        self.hide()
        username = self.userLogin.username.text()
        password = self.userLogin.password.text()
        if op.login(username, password):
            if self.setTime:
                self.timeSetting = TimeSetting()
                self.timeSetting.show()
            else:
                self.employeeManage = EmployeeManage()
                self.employeeManage.show()
        else:
            QMessageBox.information(self, '信息', '用户名或密码不正确', QMessageBox.Yes)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    userLogin = UserLogin()
    userLogin.show()
    sys.exit(app.exec_())
