# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QMessageBox
from cv2 import cv2

from clock.interface.checkInManage import CheckInManage
from clock.interface.addendanceRecord import AddendanceRecord
from interface.userLogin import UserLogin

from service import hr_service as hr
import operateMain as op


class Ui_main(QMainWindow):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(598, 261)
        self.exit = QtWidgets.QPushButton(main)
        self.exit.setGeometry(QtCore.QRect(240, 210, 111, 23))
        self.exit.setObjectName("exit")
        self.Title = QtWidgets.QCommandLinkButton(main)
        self.Title.setGeometry(QtCore.QRect(40, 20, 185, 41))
        self.Title.setObjectName("Title")
        self.alert = QtWidgets.QLabel(main)
        self.alert.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.alert.setObjectName("alert")
        self.layoutWidget = QtWidgets.QWidget(main)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 110, 521, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkIn = QtWidgets.QPushButton(self.layoutWidget)
        self.checkIn.setObjectName("checkIn")
        self.horizontalLayout.addWidget(self.checkIn)
        self.checkRecord = QtWidgets.QPushButton(self.layoutWidget)
        self.checkRecord.setObjectName("checkRecord")
        self.horizontalLayout.addWidget(self.checkRecord)
        self.employeeManage = QtWidgets.QPushButton(self.layoutWidget)
        self.employeeManage.setObjectName("employeeManage")
        self.horizontalLayout.addWidget(self.employeeManage)
        self.attendanceRecord = QtWidgets.QPushButton(self.layoutWidget)
        self.attendanceRecord.setObjectName("attendanceRecord")
        self.horizontalLayout.addWidget(self.attendanceRecord)

        self.retranslateUi(main)
        self.exit.clicked.connect(self.close)
        self.checkIn.clicked.connect(self.check_in)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.exit.setText(_translate("main", "退出"))
        self.Title.setText(_translate("main", "智能打卡系统"))
        self.alert.setText(_translate("main", "请选择..."))
        self.checkIn.setText(_translate("main", "打卡"))
        self.checkRecord.setText(_translate("main", "查看记录"))
        self.employeeManage.setText(_translate("main", "员工管理"))
        self.attendanceRecord.setText(_translate("main", "考勤报表"))

    def close(self):
        result = QMessageBox.information(self, '信息', '确定退出吗？', QMessageBox.Yes | QMessageBox.No)
        if result == QMessageBox.Yes:
            sys.exit()

    def check_in(self):
        op.face_clock()


class Main(QMainWindow):
    def __init__(self, parent=None):
        super(Main, self).__init__(parent)
        self.main = Ui_main()
        self.main.setupUi(self)
        self.main.checkRecord.clicked.connect(self.show_chickInManage)
        self.main.employeeManage.clicked.connect(self.show_userLogin)
        self.main.attendanceRecord.clicked.connect(self.show_addendanceRecord)

    def show_chickInManage(self):
        self.hide()
        self.chickInManage = CheckInManage()
        self.chickInManage.show()

    def show_addendanceRecord(self):
        self.hide()
        self.addendanceRecord = AddendanceRecord()
        self.addendanceRecord.show()

    def show_userLogin(self):
        self.userLogin = UserLogin()
        self.userLogin.show()


if __name__ == "__main__":
    hr.load_emp_data()  # 数据初始化
    app = QApplication(sys.argv)
    main = Main()
    main.show()
    sys.exit(app.exec_())
